"""
CVhelper.ai — Backend v8 (Fully Unique + Full Language Edition)
Fix: course structure (modules, class titles, topics) is generated by AI
      per skill — guaranteed unique content for every single course.
AI Engine: Gemini (free) → Groq (free fallback)
"""
import os, json, re, subprocess, tempfile, base64, traceback
from pathlib import Path
from flask import Flask, request, jsonify
from flask_cors import CORS
import requests as http
from fpdf import FPDF

try:
    from dotenv import load_dotenv
    load_dotenv(Path(__file__).parent / ".env")
except Exception:
    pass

BASE_DIR     = os.path.dirname(os.path.abspath(__file__))
PPTX_JS      = os.path.join(BASE_DIR, "gen.js")
GEMINI_MODEL = "gemini-2.0-flash"
GEMINI_URL   = f"https://generativelanguage.googleapis.com/v1beta/models/{GEMINI_MODEL}:generateContent"
GROQ_URL     = "https://api.groq.com/openai/v1/chat/completions"
GROQ_MODEL   = "llama-3.3-70b-versatile"

app = Flask(__name__)

def get_level_instruction(level, topic):
    """Persona and constraints based on course level."""
    configs = {
        "Beginner":     {"role": "Patient Technical Mentor",      "focus": "Basic syntax, why it matters, and analogies.",            "avoid": "Avoid complex architecture or deep optimization."},
        "Intermediate": {"role": "Senior Software Engineer",       "focus": "Best practices, real-world use cases, and modularity.",   "avoid": "Avoid basic definitions like what is a variable."},
        "Advanced":     {"role": "Principal Systems Architect",    "focus": "Performance, security, low-level theory, scalability.",   "avoid": "Skip all basics. Focus on edge cases and advanced patterns."},
    }
    c = configs.get(level, configs["Beginner"])
    return f"Act as a {c['role']}. Focus on: {c['focus']} {c['avoid']}"

CORS(app, origins="*")

@app.after_request
def cors_headers(r):
    r.headers["Access-Control-Allow-Origin"]  = "*"
    r.headers["Access-Control-Allow-Headers"] = "Content-Type"
    r.headers["Access-Control-Allow-Methods"] = "GET, POST, OPTIONS"
    return r

# ═══════════════════════════════════════════════════════════════
#  AI ENGINE
# ═══════════════════════════════════════════════════════════════

def call_gemini(messages, max_tokens=2000, temp=0.7):
    key = os.environ.get("GEMINI_API_KEY", "").strip()
    if not key:
        raise ValueError("GEMINI_API_KEY not set")
    contents, system_text = [], ""
    for m in messages:
        role, content = m.get("role", "user"), m.get("content", "")
        if role == "system":
            system_text = content
        elif role == "user":
            contents.append({"role": "user",  "parts": [{"text": content}]})
        elif role == "assistant":
            contents.append({"role": "model", "parts": [{"text": content}]})
    if system_text and contents:
        contents[0]["parts"][0]["text"] = system_text + "\n\n" + contents[0]["parts"][0]["text"]
    elif system_text:
        contents = [{"role": "user", "parts": [{"text": system_text}]}]
    if not contents:
        raise ValueError("No messages")
    r = http.post(
        f"{GEMINI_URL}?key={key}",
        headers={"Content-Type": "application/json"},
        json={"contents": contents,
              "generationConfig": {"temperature": temp, "maxOutputTokens": max_tokens}},
        timeout=120
    )
    r.raise_for_status()
    data       = r.json()
    candidates = data.get("candidates", [])
    if not candidates:
        raise ValueError(f"Gemini: no candidates. {data}")
    parts = candidates[0].get("content", {}).get("parts", [])
    if not parts:
        raise ValueError(f"Gemini: empty parts. finishReason={candidates[0].get('finishReason')}")
    return parts[0]["text"].strip()

def call_groq(messages, max_tokens=2000, temp=0.7):
    key = os.environ.get("GROQ_API_KEY", "").strip()
    if not key:
        raise ValueError("GROQ_API_KEY not set")
    r = http.post(GROQ_URL,
        headers={"Authorization": f"Bearer {key}", "Content-Type": "application/json"},
        json={"model": GROQ_MODEL, "messages": messages,
              "max_tokens": max_tokens, "temperature": temp},
        timeout=90)
    r.raise_for_status()
    return r.json()["choices"][0]["message"]["content"].strip()

def ai(messages, max_tokens=2000, temp=0.7):
    engine    = os.environ.get("AI_ENGINE", "auto").lower()
    gem_key   = os.environ.get("GEMINI_API_KEY", "").strip()
    groq_key  = os.environ.get("GROQ_API_KEY",   "").strip()
    if engine == "gemini": return call_gemini(messages, max_tokens, temp)
    if engine == "groq":   return call_groq(messages, max_tokens, temp)
    last_err = None
    if gem_key:
        try:   return call_gemini(messages, max_tokens, temp)
        except Exception as e:
            last_err = e
            if groq_key: print(f"[CVhelper] Gemini failed ({e}), trying Groq…")
    if groq_key:
        try:   return call_groq(messages, max_tokens, temp)
        except Exception as e: last_err = e
    raise ValueError(f"All AI engines failed. Last: {last_err}")

def groq(messages, max_tokens=2000, temp=0.7):
    return ai(messages, max_tokens, temp)

# ═══════════════════════════════════════════════════════════════
#  JSON EXTRACTOR
# ═══════════════════════════════════════════════════════════════

def extract_json(text):
    if not text: raise ValueError("Empty AI response")
    text = text.strip()
    m = re.search(r"```(?:json)?\s*([\s\S]+?)```", text)
    if m: text = m.group(1).strip()

    def try_parse(s):
        try: return json.loads(s)
        except json.JSONDecodeError:
            s2 = re.sub(r',\s*([\}\]])', r'\1', s)
            s2 = re.sub(r'[\x00-\x08\x0b\x0c\x0e-\x1f\x7f]', '', s2)
            return json.loads(s2)

    depth = start = -1
    for i, ch in enumerate(text):
        if ch == '{':
            if start == -1: start = i
            depth = (depth or 0) + 1
        elif ch == '}' and start != -1:
            depth -= 1
            if depth == 0:
                try: return try_parse(text[start:i+1])
                except Exception: start = depth = -1

    s, e = text.find("{"), text.rfind("}")
    if s != -1 and e > s: return try_parse(text[s:e+1])
    raise ValueError(f"No JSON in: {text[:200]}")

# ═══════════════════════════════════════════════════════════════
#  WEB SEARCH  (Wikipedia + DuckDuckGo — both free, no key)
# ═══════════════════════════════════════════════════════════════

def search_wikipedia(query):
    """Search Wikipedia for a topic and return its summary."""
    try:
        search_url = "https://en.wikipedia.org/w/api.php"
        sr = http.get(search_url, params={
            "action": "query", "list": "search",
            "srsearch": query, "srlimit": 1, "format": "json"
        }, timeout=8, headers={"User-Agent": "CVhelper.ai/1.0"})
        sr.raise_for_status()
        results = sr.json().get("query", {}).get("search", [])
        if not results:
            return ""
        title = results[0]["title"]
        pr = http.get(search_url, params={
            "action": "query", "prop": "extracts",
            "exintro": True, "explaintext": True,
            "titles": title, "format": "json"
        }, timeout=8, headers={"User-Agent": "CVhelper.ai/1.0"})
        pr.raise_for_status()
        pages = pr.json().get("query", {}).get("pages", {})
        for page in pages.values():
            extract = page.get("extract", "")
            if extract and len(extract) > 100:
                return f"[Wikipedia: {title}]\n{extract[:1000]}"
    except Exception as e:
        print(f"[Wikipedia search] {e}")
    return ""

def search_duckduckgo(query):
    """DuckDuckGo instant answer — free, no key needed."""
    try:
        r = http.get("https://api.duckduckgo.com/", params={
            "q": query, "format": "json",
            "no_redirect": 1, "no_html": 1, "skip_disambig": 1
        }, timeout=8, headers={"User-Agent": "CVhelper.ai/1.0"})
        r.raise_for_status()
        data = r.json()
        text = ""
        if data.get("AbstractText"):
            text += f"[{data.get('Heading',query)}]: {data['AbstractText'][:600]}\n"
        for t in data.get("RelatedTopics", [])[:3]:
            if isinstance(t, dict) and t.get("Text") and len(t["Text"]) > 40:
                text += f"- {t['Text'][:300]}\n"
        return text.strip()
    except Exception as e:
        print(f"[DDG search] {e}")
    return ""

def fetch_real_knowledge(topic, course_title):
    """Fetch real educational content about a topic from the web."""
    queries = [
        f"{topic} {course_title}",
        f"what is {topic}",
        f"{topic} explained"
    ]
    knowledge = ""
    for q in queries[:2]:
        wiki = search_wikipedia(q)
        if wiki and len(wiki) > 100:
            knowledge += wiki + "\n\n"
            break
    ddg = search_duckduckgo(f"{topic} {course_title}")
    if ddg and len(ddg) > 50:
        knowledge += ddg
    return knowledge.strip() or f"Topic: {topic} in the context of {course_title}."

# ═══════════════════════════════════════════════════════════════
#  SINGLE-TOPIC AI CALL  ← THE KEY FIX
# ═══════════════════════════════════════════════════════════════

def generate_topic_content(topic, course_title, class_title, level, lang, position, total, level_instruction=None):
    """Generate rich, unique content for ONE topic only — always in English."""
    print(f"  [topic {position}/{total}] Researching: {topic}")
    knowledge = fetch_real_knowledge(topic, course_title)
    print(f"  [topic {position}/{total}] Got {len(knowledge)} chars of web content")

    persona_note = f"TEACHING PERSONA: {level_instruction}" if level_instruction else ""

    prompt = (
        f"You are an expert educator. Write educational content about ONE specific topic.\n"
        f"{persona_note}\n\n"
        f"Topic: {topic}\n"
        f"Course: {course_title}\n"
        f"Class: {class_title}\n"
        f"Level: {level}\n"
        f"Position in class: {position} of {total} topics\n\n"
        f"REFERENCE MATERIAL FROM THE WEB:\n{knowledge}\n\n"
        f"Write a detailed educational section about '{topic}' using the reference material.\n"
        f"IMPORTANT: This is topic #{position} in the class. Do NOT repeat content from other topics.\n"
        f"Focus ONLY on '{topic}' — make the content specific, factual, and unique to this topic.\n"
        f"Do NOT use generic placeholder phrases. Write real, specific, factual content.\n\n"
        f"Return ONLY this JSON — no markdown, no extra text:\n"
        f'{{\n'
        f'  "heading": "{topic}",\n'
        f'  "body": "3-4 sentences explaining {topic} with a clear definition, a real-world example, and why it matters in {course_title}",\n'
        f'  "bullets": [\n'
        f'    "A specific, verified fact about {topic}",\n'
        f'    "How professionals use {topic} in real work",\n'
        f'    "The most common beginner mistake with {topic} and how to avoid it",\n'
        f'    "One expert tip for mastering {topic}"\n'
        f'  ]\n'
        f'}}'
    )

    try:
        raw  = ai([{"role": "user", "content": prompt}], max_tokens=1000, temp=0.7)
        data = extract_json(raw)

        body    = data.get("body", "")
        bullets = data.get("bullets", [])
        heading = data.get("heading", topic)

        bad_phrases = ["write ", "Write ", "3-4 sentences", "complete sentence",
                       "specific verified fact", "concrete real-world", "topic name"]
        if any(p in body for p in bad_phrases) or len(body) < 60:
            raise ValueError(f"Placeholder text detected for: {topic}")

        return {"heading": heading, "body": body, "bullets": bullets[:4]}

    except Exception as e:
        print(f"  [topic {position}/{total}] AI failed: {e}, using fallback")
        lines = [l.strip() for l in knowledge.split('\n') if len(l.strip()) > 40]
        body  = " ".join(lines[:3])[:400] if lines else (
            f"{topic} is a fundamental concept in {course_title}. "
            f"Mastering {topic} enables you to work confidently and professionally."
        )
        return {
            "heading": topic,
            "body":    body,
            "bullets": [
                f"{topic} is a core building block in {course_title}",
                f"Professionals apply {topic} to improve quality and efficiency",
                f"Beginners often overlook {topic} — focus on understanding the why",
                f"Daily practice of {topic} leads to faster mastery"
            ]
        }

# ═══════════════════════════════════════════════════════════════
#  LANGUAGE MAP
# ═══════════════════════════════════════════════════════════════

LANGUAGE_MAP = {
    "hindi":"Hindi","हिंदी":"Hindi","हिन्दी":"Hindi",
    "bengali":"Bengali","bangla":"Bengali","বাংলা":"Bengali",
    "tamil":"Tamil","தமிழ்":"Tamil",
    "telugu":"Telugu","తెలుగు":"Telugu",
    "marathi":"Marathi","मराठी":"Marathi",
    "gujarati":"Gujarati","ગુજરાતી":"Gujarati",
    "kannada":"Kannada","ಕನ್ನಡ":"Kannada",
    "malayalam":"Malayalam","മലയാളം":"Malayalam",
    "punjabi":"Punjabi","ਪੰਜਾਬੀ":"Punjabi",
    "urdu":"Urdu","اردو":"Urdu",
    "sanskrit":"Sanskrit","संस्कृत":"Sanskrit",
    "odia":"Odia","oriya":"Odia","ଓଡ଼ିଆ":"Odia",
    "assamese":"Assamese","অসমীয়া":"Assamese",
    "french":"French","spanish":"Spanish","español":"Spanish",
    "german":"German","deutsch":"German","japanese":"Japanese",
    "chinese":"Chinese","arabic":"Arabic","portuguese":"Portuguese",
    "russian":"Russian","korean":"Korean","italian":"Italian",
}

def detect_language(text):
    if not text: return "English"
    lower = text.lower()
    for kw, lang in LANGUAGE_MAP.items():
        if kw in lower: return lang
    return "English"

# ═══════════════════════════════════════════════════════════════
#  PDF  (unicode safe)
# ═══════════════════════════════════════════════════════════════

def safe_str(text, maxlen=None):
    if not text: return ""
    text = str(text)
    if maxlen: text = text[:maxlen]
    try:
        text.encode("latin-1")
        return text
    except (UnicodeEncodeError, UnicodeDecodeError):
        return text.encode("ascii", errors="replace").decode("ascii")

def make_pdf(course_title, module_title, class_title, key_points, objectives):
    pdf = FPDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.set_fill_color(109, 74, 255)
    pdf.rect(0, 0, 210, 25, "F")
    pdf.set_font("Helvetica", "B", 16)
    pdf.set_text_color(255, 255, 255)
    pdf.set_xy(10, 7)
    pdf.cell(0, 10, "CVhelper.ai - Course Notes", ln=True)
    pdf.set_font("Helvetica", "", 9)
    pdf.set_xy(10, 17)
    pdf.cell(0, 5, f"Module: {safe_str(module_title,40)}  |  Class: {safe_str(class_title,40)}", ln=True)
    pdf.set_text_color(20, 20, 40)
    pdf.set_xy(10, 32)
    pdf.set_font("Helvetica", "B", 18)
    pdf.cell(0, 10, safe_str(course_title, 50), ln=True)
    pdf.set_font("Helvetica", "B", 13)
    pdf.set_text_color(109, 74, 255)
    pdf.cell(0, 8, safe_str(class_title, 60), ln=True)
    pdf.ln(4)
    pdf.set_draw_color(109, 74, 255)
    pdf.set_line_width(0.8)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(6)
    pdf.set_font("Helvetica", "B", 12)
    pdf.set_text_color(20, 20, 40)
    pdf.cell(0, 8, "Learning Objectives", ln=True)
    pdf.set_font("Helvetica", "", 11)
    pdf.set_text_color(60, 60, 80)
    for obj in (objectives or [])[:4]:
        pdf.set_x(14); pdf.cell(5, 7, chr(149), ln=False)
        pdf.multi_cell(0, 7, safe_str(str(obj), 120))
    pdf.ln(4)
    pdf.set_line_width(0.4)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(5)
    pdf.set_font("Helvetica", "B", 12)
    pdf.set_text_color(20, 20, 40)
    pdf.cell(0, 8, "Class Notes", ln=True)
    pdf.ln(2)
    for i, pt in enumerate((key_points or [])[:10]):
        h = pt.get("heading", f"Point {i+1}") if isinstance(pt, dict) else f"Point {i+1}"
        b = pt.get("body", "") if isinstance(pt, dict) else str(pt)
        pdf.set_fill_color(235, 230, 255)
        pdf.set_font("Helvetica", "B", 11)
        pdf.set_text_color(60, 30, 160)
        pdf.set_x(10)
        pdf.cell(190, 8, f"  {safe_str(h, 60)}", fill=True, ln=True)
        pdf.set_font("Helvetica", "", 10.5)
        pdf.set_text_color(40, 40, 60)
        pdf.set_x(14)
        pdf.multi_cell(186, 6.5, safe_str(str(b), 600))
        if isinstance(pt, dict) and pt.get("bullets"):
            pdf.set_font("Helvetica", "", 9.5)
            pdf.set_text_color(80, 80, 100)
            for bull in pt["bullets"][:5]:
                pdf.set_x(18); pdf.cell(5, 6, chr(149), ln=False)
                pdf.multi_cell(0, 6, safe_str(str(bull), 100))
        pdf.ln(3)
    pdf.set_y(-20)
    pdf.set_font("Helvetica", "I", 8)
    pdf.set_text_color(150, 150, 160)
    pdf.cell(0, 8, f"CVhelper.ai  |  {safe_str(course_title, 40)}", align="C")
    return pdf.output()

# ═══════════════════════════════════════════════════════════════
#  PPTX
# ═══════════════════════════════════════════════════════════════

def run_pptx(data_dict):
    tmp_json = tmp_pptx = None
    try:
        with tempfile.NamedTemporaryFile(mode="w", suffix=".json",
                                         delete=False, encoding="utf-8") as f:
            json.dump(data_dict, f, ensure_ascii=False)
            tmp_json = f.name
        tmp_pptx = tmp_json.replace(".json", ".pptx")
        res = subprocess.run(
            ["node", PPTX_JS, tmp_json, tmp_pptx],
            capture_output=True, text=True, timeout=60
        )
        if res.returncode != 0:
            raise RuntimeError(res.stderr or res.stdout or "node error")
        if not os.path.exists(tmp_pptx):
            raise RuntimeError("PPTX not created")
        with open(tmp_pptx, "rb") as f:
            return base64.b64encode(f.read()).decode()
    finally:
        for p in [tmp_json, tmp_pptx]:
            if p:
                try: os.unlink(p)
                except Exception: pass

# ═══════════════════════════════════════════════════════════════
#  ROUTES
# ═══════════════════════════════════════════════════════════════

@app.route("/")
def index():
    path = os.path.join(BASE_DIR, "index.html")
    with open(path, "r", encoding="utf-8") as f:
        return f.read(), 200, {"Content-Type": "text/html; charset=utf-8"}

@app.route("/api/health")
def health():
    routes      = sorted(str(r) for r in app.url_map.iter_rules() if r.rule.startswith("/api"))
    gem_key     = bool(os.environ.get("GEMINI_API_KEY", ""))
    groq_key    = bool(os.environ.get("GROQ_API_KEY", ""))
    engine_pref = os.environ.get("AI_ENGINE", "auto").lower()
    if   engine_pref == "gemini": active = "Gemini"         if gem_key  else "none"
    elif engine_pref == "groq":   active = "Groq"           if groq_key else "none"
    else:                         active = "Gemini (auto)"  if gem_key  else ("Groq (auto)" if groq_key else "none")
    return jsonify({
        "status": "ok", "version": "v9",
        "engine": active,
        "gemini_key_set": gem_key,
        "groq_key_set":   groq_key,
        "key_set":        gem_key or groq_key,
        "routes":         routes
    })

@app.route("/api/test")
def test_ai():
    gem_key  = os.environ.get("GEMINI_API_KEY", "")
    groq_key = os.environ.get("GROQ_API_KEY",   "")
    if not gem_key and not groq_key:
        return jsonify({"ok": False,
            "error": "No key. Add GEMINI_API_KEY (aistudio.google.com) or GROQ_API_KEY (console.groq.com) to .env"})
    try:
        reply  = ai([{"role": "user", "content": "Say OK"}], max_tokens=10, temp=0)
        engine = "Gemini" if gem_key else "Groq"
        return jsonify({"ok": True, "reply": reply, "engine": engine})
    except Exception as e:
        return jsonify({"ok": False, "error": str(e)})

# ═══════════════════════════════════════════════════════════════
#  GENERATE COURSE STRUCTURE  ← FULLY AI-DRIVEN (THE BIG FIX)
# ═══════════════════════════════════════════════════════════════

def build_fallback_structure(skill, level):
    """
    Emergency fallback: build a skill-specific structure without AI.
    Still uses the skill name so modules/classes are not totally generic.
    """
    return [
        {
            "mod_title": f"Module 1: Introduction to {skill}",
            "mod_desc":  f"Understand what {skill} is, its history, and why it matters.",
            "classes": [
                {"title": f"What is {skill} and Why It Matters",       "topics": [f"Definition of {skill}", f"Real-world uses of {skill}", f"Who uses {skill}"]},
                {"title": f"History and Evolution of {skill}",          "topics": [f"Origins of {skill}", f"How {skill} has changed over time", "Current state of the field"]},
            ],
        },
        {
            "mod_title": f"Module 2: Core Concepts of {skill}",
            "mod_desc":  f"Build a solid foundation by mastering the essential principles of {skill}.",
            "classes": [
                {"title": f"Fundamental Principles of {skill}",         "topics": [f"Key principles of {skill}", "Common terminology", "How the basics fit together"]},
                {"title": f"Essential {skill} Techniques",              "topics": [f"Primary techniques in {skill}", "Step-by-step walkthroughs", "Avoiding beginner mistakes"]},
            ],
        },
        {
            "mod_title": f"Module 3: Practical Application of {skill}",
            "mod_desc":  f"Apply your {skill} knowledge to real-world scenarios and projects.",
            "classes": [
                {"title": f"Applying {skill} in Real Projects",         "topics": [f"Planning a {skill} project", "Executing effectively", "Reviewing outcomes"]},
                {"title": f"Tools and Workflows for {skill}",           "topics": [f"Best tools for {skill}", "Professional workflows", "Increasing efficiency"]},
            ],
        },
        {
            "mod_title": f"Module 4: Advanced {skill} and Mastery",
            "mod_desc":  f"Reach professional-level skill and explore advanced topics in {skill}.",
            "classes": [
                {"title": f"Advanced {skill} Strategies",               "topics": [f"Advanced concepts in {skill}", "Expert-level tips", "Performance and optimization"]},
                {"title": f"Capstone: Your {skill} Portfolio Project",  "topics": ["Planning your project", "Building and presenting", "Next steps in your learning journey"]},
            ],
        },
    ]

def generate_course_structure_with_ai(skill, level, lang, duration):
    """
    Ask the AI to generate a UNIQUE, skill-specific 4-module course structure.
    Each call produces completely different modules, class titles, and topics.
    """
    prompt = f"""You are a world-class curriculum designer. Design a complete, unique course structure in English.

Skill: "{skill}"
Level: {level}
Duration: {duration}

Rules:
- Generate EXACTLY 4 modules, each with EXACTLY 2 teaching classes.
- Every module title, class title, and topic must be SPECIFIC to "{skill}".
- Do NOT use generic titles like "Introduction", "Module 1", "Basics", "Advanced Techniques", "Tools", "Best Practices", "Capstone". Be specific.
- Each class must have EXACTLY 3 topics that are real, specific sub-topics of "{skill}".
- No two classes may have the same title or topics.
- The progression must make sense: foundations → core concepts → practical application → mastery.

Return ONLY this JSON — no markdown, no extra text:
{{
  "title": "Unique engaging course title for {skill}",
  "subtitle": "One-line subtitle describing what students will achieve",
  "description": "Two sentences about what students will learn and why this course is valuable.",
  "whatYouLearn": [
    "Specific outcome 1 unique to {skill}",
    "Specific outcome 2 unique to {skill}",
    "Specific outcome 3 unique to {skill}",
    "Specific outcome 4 unique to {skill}",
    "Specific outcome 5 unique to {skill}",
    "Specific outcome 6 unique to {skill}"
  ],
  "requirements": ["requirement 1 for {skill}", "requirement 2 for {skill}"],
  "modules": [
    {{
      "title": "Unique module title specific to {skill} (not just 'Module 1')",
      "description": "One sentence describing what this module covers.",
      "classes": [
        {{
          "title": "Specific class title (not generic)",
          "topics": ["Specific topic A", "Specific topic B", "Specific topic C"]
        }},
        {{
          "title": "Another specific class title",
          "topics": ["Specific topic D", "Specific topic E", "Specific topic F"]
        }}
      ]
    }},
    {{
      "title": "Unique module 2 title",
      "description": "One sentence.",
      "classes": [
        {{"title": "Class title", "topics": ["Topic G", "Topic H", "Topic I"]}},
        {{"title": "Class title", "topics": ["Topic J", "Topic K", "Topic L"]}}
      ]
    }},
    {{
      "title": "Unique module 3 title",
      "description": "One sentence.",
      "classes": [
        {{"title": "Class title", "topics": ["Topic M", "Topic N", "Topic O"]}},
        {{"title": "Class title", "topics": ["Topic P", "Topic Q", "Topic R"]}}
      ]
    }},
    {{
      "title": "Unique module 4 title",
      "description": "One sentence.",
      "classes": [
        {{"title": "Class title", "topics": ["Topic S", "Topic T", "Topic U"]}},
        {{"title": "Class title", "topics": ["Topic V", "Topic W", "Topic X"]}}
      ]
    }}
  ]
}}"""

    raw  = ai([{"role": "user", "content": prompt}], max_tokens=2500, temp=0.8)
    data = extract_json(raw)

    # Validate we got real modules back
    modules_raw = data.get("modules", [])
    if not isinstance(modules_raw, list) or len(modules_raw) < 2:
        raise ValueError("AI returned invalid module structure")

    # Normalise into the internal structure format
    structure = []
    for mod in modules_raw[:4]:
        classes_raw = mod.get("classes", [])
        if not isinstance(classes_raw, list):
            classes_raw = []
        classes = []
        for cls in classes_raw[:2]:
            title  = cls.get("title", "")
            topics = cls.get("topics", [])
            if not title or not isinstance(topics, list) or len(topics) < 1:
                continue
            classes.append({"title": title, "topics": topics[:3]})
        if not classes:
            continue
        structure.append({
            "mod_title": mod.get("title", ""),
            "mod_desc":  mod.get("description", ""),
            "classes":   classes,
        })

    if len(structure) < 2:
        raise ValueError("Not enough valid modules from AI")

    return data, structure   # return both full meta and structure


@app.route("/api/generate-course", methods=["POST", "OPTIONS"])
def generate_course():
    if request.method == "OPTIONS": return "", 204
    body  = request.get_json(force=True) or {}
    skill = (body.get("skill") or "").strip()
    level = (body.get("level") or "Beginner").strip()
    dur   = (body.get("duration") or "4 weeks").strip()
    if not skill: return jsonify({"error": "skill required"}), 400

    lang = "English"

    # ══════════════════════════════════════════════════════════════
    #  STEP 1: AI generates the ENTIRE unique course structure.
    #  All module titles, class titles, and topics are skill-specific.
    # ══════════════════════════════════════════════════════════════
    print(f"[generate_course] Generating unique AI course structure for: {skill}")
    meta     = {}
    structure = None
    try:
        meta, structure = generate_course_structure_with_ai(skill, level, lang, dur)
        print(f"[generate_course] AI structure OK — {len(structure)} modules")
    except Exception as e:
        print(f"[generate_course] AI structure failed ({e}), using fallback")
        structure = build_fallback_structure(skill, level)

    # ══════════════════════════════════════════════════════════════
    #  STEP 2: Build the modules array from the AI structure
    # ══════════════════════════════════════════════════════════════
    fid = re.sub(r"[^a-z0-9]", "_", skill.lower())[:20]

    modules = []
    for mi, s in enumerate(structure):
        classes = []
        for ci, c in enumerate(s["classes"]):
            classes.append({
                "id":            ci + 1,
                "title":         c["title"],
                "duration":      "45 min",
                "type":          "video",
                "description":   "",
                "topics":        c["topics"],
                "hasVideo":      True,
                "hasNotes":      True,
                "hasPPT":        True,
                "hasAssignment": False,
            })
        # Add a quiz class at the end of each module
        classes.append({
            "id":            len(classes) + 1,
            "title":         f"Module {mi + 1} Quiz",
            "duration":      "30 min",
            "type":          "assignment",
            "description":   "",
            "topics":        [s["mod_title"], f"Module {mi + 1} Review"],
            "hasVideo":      False,
            "hasNotes":      True,
            "hasPPT":        False,
            "hasAssignment": True,
        })
        modules.append({
            "id":          mi + 1,
            "title":       s["mod_title"],
            "description": s["mod_desc"],
            "duration":    "1 week",
            "classes":     classes,
        })

    # ══════════════════════════════════════════════════════════════
    #  STEP 3: Build final course object — prefer AI meta if available
    # ══════════════════════════════════════════════════════════════
    course = {
        "id":           fid,
        "title":        meta.get("title")        or f"Complete {skill} Course",
        "subtitle":     meta.get("subtitle")     or f"A {level} course on {skill}",
        "category":     "Personal Development",
        "emoji":        "📚",
        "color":        "#6D4AFF",
        "level":        level,
        "duration":     dur,
        "totalClasses": sum(len(m["classes"]) for m in modules),
        "totalHours":   10,
        "description":  meta.get("description")  or f"Learn {skill} step by step in this {level} course.",
        "whatYouLearn": meta.get("whatYouLearn") or [
            f"Core concepts of {skill}", "Practical techniques",
            "Real-world applications",  "Best practices",
            "Common mistakes to avoid", "Advanced tips",
        ],
        "requirements": meta.get("requirements") or ["No experience needed", "Willingness to learn"],
        "skill":        skill,
        "lang":         "English",
        "modules":      modules,
    }
    return jsonify({"ok": True, "course": course})


# ─── GENERATE CLASS CONTENT ──────────────────────────────────
@app.route("/api/generate-class-content", methods=["POST", "OPTIONS"])
def generate_class_content():
    if request.method == "OPTIONS": return "", 204
    body         = request.get_json(force=True) or {}
    course_title = body.get("courseTitle", "")
    module_title = body.get("moduleTitle", "")
    class_title  = body.get("classTitle",  "")
    topics_list  = body.get("topics", [])
    level        = body.get("level", "Beginner")
    topics_str   = ", ".join(topics_list) if topics_list else class_title
    t1 = topics_list[0] if len(topics_list) > 0 else class_title
    t2 = topics_list[1] if len(topics_list) > 1 else t1
    t3 = topics_list[2] if len(topics_list) > 2 else t1
    t4 = topics_list[3] if len(topics_list) > 3 else t1
    lang = "English"

    print(f"[class-content] Generating unique content for: {class_title}")
    unique_topics = list(dict.fromkeys([t1, t2, t3, t4]))  # deduplicate, preserve order

    key_points = []
    for i, topic in enumerate(unique_topics):
        level_instruction = get_level_instruction(level, topic)
        kp = generate_topic_content(
            topic             = topic,
            course_title      = course_title,
            class_title       = class_title,
            level             = level,
            lang              = lang,
            position          = i + 1,
            total             = len(unique_topics),
            level_instruction = level_instruction
        )
        key_points.append(kp)

    overview_prompt = (
        f"""You are an expert educator. Write a class overview in English.

Course: {course_title}
Class: {class_title}
Topics covered: {topics_str}
Level: {level}

IMPORTANT: Write unique, specific content. Do NOT repeat the same sentences across sections.
Each section must contain distinct information about different aspects of this class.

Return ONLY valid JSON:
{{
  "videoScript": "2-3 engaging paragraphs introducing this class. Start with an interesting fact specific to {class_title}. Explain what students will learn from each topic. End with motivation.",
  "objectives": [
    "Understand the core principles of {t1} and apply them confidently",
    "Use {t2} techniques in real-world {course_title} scenarios",
    "Identify and avoid the 3 most common mistakes in {class_title}",
    "Build hands-on skills in {t3} through structured practice"
  ],
  "summary": "2-3 sentences describing the specific skills students gained and how these topics connect within {course_title}.",
  "nextSteps": [
    "Practice {t1} for 20 minutes using a real project",
    "Review the key differences between {t2} and related concepts",
    "Experiment with {t3} in a hands-on exercise",
    "Preview the next class topics and note any questions"
  ],
  "realWorldExample": "A specific, detailed real scenario where a professional uses {class_title} skills in their daily work.",
  "keyStats": [
    "A real, specific fact or statistic about {t1}",
    "A real, specific fact or statistic about {t2}",
    "A measurable impact statistic about mastering {class_title}"
  ]
}}"""
    )

    try:
        raw_ov   = ai([{"role": "user", "content": overview_prompt}], max_tokens=1200, temp=0.6)
        overview = extract_json(raw_ov)
    except Exception as e:
        print(f"[class-content] Overview generation failed: {e}")
        overview = {}

    content = {
        "videoScript":       overview.get("videoScript", f"Welcome to {class_title}. In this class we explore {topics_str} — essential skills for any {course_title} practitioner."),
        "keyPoints":         key_points,
        "objectives":        overview.get("objectives", [
                                f"Understand {t1} and explain it clearly",
                                f"Apply {t2} in practical exercises",
                                f"Avoid common mistakes in {class_title}",
                                f"Build skills for advanced {course_title} topics"]),
        "summary":           overview.get("summary", f"In this class we covered {topics_str}. You now have solid knowledge to move forward in {course_title}."),
        "nextSteps":         overview.get("nextSteps", [
                                f"Practice {t1} for 20 minutes",
                                f"Read more about {t2}",
                                f"Apply {t3} in a project",
                                "Prepare for the next class"]),
        "diagramData":       {"type": "flow"},
        "realWorldExample":  overview.get("realWorldExample", f"Professionals in {course_title} use {class_title} skills every day to deliver high-quality work."),
        "keyStats":          overview.get("keyStats", [
                                f"Mastering {t1} increases productivity significantly",
                                f"Most experts say {t2} is the most important concept to learn first",
                                f"Daily practice of {class_title} skills leads to mastery in 30 days"])
    }

    return jsonify({"ok": True, "content": content})

# ─── GENERATE MCQ ─────────────────────────────────────────────
@app.route("/api/generate-mcq", methods=["POST", "OPTIONS"])
def generate_mcq():
    if request.method == "OPTIONS": return "", 204
    body         = request.get_json(force=True) or {}
    course_title = body.get("courseTitle", "")
    module_title = body.get("moduleTitle", "")
    class_title  = body.get("classTitle",  "")
    topics_list  = body.get("topics", [])
    kp_raw       = body.get("keyPoints", [])
    kp_headings  = [k.get("heading","") if isinstance(k, dict) else str(k) for k in kp_raw[:5]]
    topics_str   = ", ".join(topics_list[:4]) if topics_list else class_title
    concepts_str = ", ".join(kp_headings[:4]) if kp_headings else topics_str
    lang         = "English"
    lang_note    = ""

    research = ""
    try:
        knowledge = fetch_real_knowledge(class_title, course_title)
        if knowledge and len(knowledge) > 80:
            research = f"\nREFERENCE MATERIAL:\n{knowledge[:1500]}\n"
    except Exception: pass

    prompt = f"""You are an expert quiz writer.

Class: {class_title}
Module: {module_title}
Topics: {topics_str}
Concepts: {concepts_str}
{lang_note}
{research}

Write 10 UNIQUE MCQ questions — each testing a DIFFERENT concept.
Every question must be specific and factual. No generic or repeated questions.

Return ONLY valid JSON:
{{
  "title": "Quiz: {class_title}",
  "description": "Test your knowledge of {class_title}. 70% to pass.",
  "timeLimit": 15,
  "passingScore": 70,
  "questions": [
    {{"id":1,"question":"Specific question about topic 1?","difficulty":"easy",
      "options":[{{"id":"A","text":"correct"}},{{"id":"B","text":"wrong"}},{{"id":"C","text":"wrong"}},{{"id":"D","text":"wrong"}}],
      "correct":"A","explanation":"Why A is correct."}}
  ]
}}

Write all 10 questions. Mix: Q1-3=easy, Q4-8=medium, Q9-10=hard."""

    def make_fallback_quiz():
        base = topics_list[:4] if topics_list else [class_title]*4
        qs   = []
        for i in range(10):
            t    = base[i % len(base)]
            diff = "easy" if i < 3 else ("medium" if i < 8 else "hard")
            qs.append({"id": i+1, "question": f"What is the key principle of {t}?",
                "difficulty": diff,
                "options": [
                    {"id":"A","text":f"The foundational concept of {t}"},
                    {"id":"B","text":"An unrelated idea"},
                    {"id":"C","text":"A common misconception"},
                    {"id":"D","text":"None of the above"}],
                "correct": "A",
                "explanation": f"Option A correctly identifies the core principle of {t}."})
        return {"title": f"Quiz: {class_title}",
                "description": f"Test your understanding of {class_title}.",
                "timeLimit": 15, "passingScore": 70, "questions": qs}

    try:
        raw  = ai([{"role": "user", "content": prompt}], max_tokens=3500, temp=0.5)
        quiz = extract_json(raw)
        if not isinstance(quiz.get("questions"), list) or len(quiz["questions"]) < 3:
            raise ValueError("Too few questions")
        for i, q in enumerate(quiz["questions"]):
            q.setdefault("id", i+1)
            q.setdefault("difficulty", "medium")
            q.setdefault("explanation", "Review your class notes.")
            if not isinstance(q.get("options"), list) or len(q["options"]) < 2:
                q["options"] = [{"id":"A","text":"Option A"},{"id":"B","text":"Option B"},
                                {"id":"C","text":"Option C"},{"id":"D","text":"Option D"}]
            if not q.get("correct"): q["correct"] = "A"
        return jsonify({"ok": True, "quiz": quiz})
    except Exception as e:
        traceback.print_exc()
        return jsonify({"ok": True, "quiz": make_fallback_quiz()})

# ─── CHAT ─────────────────────────────────────────────────────
@app.route("/api/chat", methods=["POST", "OPTIONS"])
def chat():
    if request.method == "OPTIONS": return "", 204
    body            = request.get_json(force=True) or {}
    messages        = body.get("messages", [])
    course_context  = body.get("courseContext",  "")
    class_context   = body.get("classContext",   "")
    content_context = body.get("contentContext", "")
    ctx_parts = []
    if course_context:  ctx_parts.append("Course: " + course_context)
    if class_context:   ctx_parts.append("Class: "  + class_context)
    if content_context: ctx_parts.append("Summary: "+ content_context[:300])
    context_str = "\n".join(ctx_parts) or "General learning assistant"
    system = (
        "You are CVhelper AI, a warm and expert learning assistant.\n"
        "Give clear, structured answers with real examples.\n"
        f"Context:\n{context_str}\n\n"
        "Use markdown for code and lists. End with encouragement."
    )
    ai_msgs = [{"role": "system", "content": system}]
    for msg in messages[-10:]:
        role    = msg.get("role", "user")
        content = (msg.get("content") or "").strip()
        if role in ("user", "assistant") and content:
            ai_msgs.append({"role": role, "content": content})
    if not any(m["role"] == "user" for m in ai_msgs[1:]):
        return jsonify({"error": "No user message"}), 400
    try:
        reply = ai(ai_msgs, max_tokens=800, temp=0.7)
        return jsonify({"ok": True, "reply": reply})
    except Exception as e:
        traceback.print_exc()
        return jsonify({"error": str(e)}), 500

# ─── PPTX / PDF ───────────────────────────────────────────────
@app.route("/api/generate-pptx", methods=["POST", "OPTIONS"])
def generate_pptx():
    if request.method == "OPTIONS": return "", 204
    body = request.get_json(force=True) or {}
    data = body.get("data")
    if not data: return jsonify({"error": "data required"}), 400
    try:
        b64   = run_pptx(data)
        title = re.sub(r"[^a-zA-Z0-9]+", "-", data.get("classTitle","class"))[:40].strip("-")
        return jsonify({"ok": True, "b64": b64, "filename": f"CVhelper-{title}.pptx"})
    except Exception as e:
        traceback.print_exc(); return jsonify({"error": str(e)}), 500

@app.route("/api/generate-course-pptx", methods=["POST", "OPTIONS"])
def generate_course_pptx():
    if request.method == "OPTIONS": return "", 204
    body   = request.get_json(force=True) or {}
    course = body.get("course")
    if not course: return jsonify({"error": "course required"}), 400
    try:
        b64   = run_pptx({"type": "full_course", "course": course})
        title = re.sub(r"[^a-zA-Z0-9]+", "-", course.get("title","course"))[:40].strip("-")
        return jsonify({"ok": True, "b64": b64, "filename": f"CVhelper-FullCourse-{title}.pptx"})
    except Exception as e:
        traceback.print_exc(); return jsonify({"error": str(e)}), 500

@app.route("/api/generate-pdf", methods=["POST", "OPTIONS"])
def generate_pdf():
    if request.method == "OPTIONS": return "", 204
    body = request.get_json(force=True) or {}
    try:
        pdf_bytes = make_pdf(
            body.get("courseTitle","Course"), body.get("moduleTitle","Module"),
            body.get("classTitle","Class"),   body.get("keyPoints",[]),
            body.get("objectives",[]))
        b64   = base64.b64encode(bytes(pdf_bytes)).decode()
        title = re.sub(r"[^a-zA-Z0-9]+", "-", body.get("classTitle","notes"))[:30].strip("-")
        return jsonify({"ok": True, "b64": b64, "filename": f"CVhelper-Notes-{title}.pdf"})
    except Exception as e:
        traceback.print_exc(); return jsonify({"error": str(e)}), 500

@app.route("/api/categories")
def categories():
    return jsonify({"categories": [
        {"name":"Technology",           "emoji":"💻","color":"#6D4AFF"},
        {"name":"Music",                "emoji":"🎵","color":"#F59E0B"},
        {"name":"Creative Arts",        "emoji":"🎨","color":"#EC4899"},
        {"name":"Cooking",              "emoji":"🍳","color":"#EF4444"},
        {"name":"Sports & Fitness",     "emoji":"⚽","color":"#10B981"},
        {"name":"Business",             "emoji":"💼","color":"#3B82F6"},
        {"name":"Language",             "emoji":"🌍","color":"#8B5CF6"},
        {"name":"Personal Development", "emoji":"🌱","color":"#06B6D4"},
        {"name":"Photography",          "emoji":"📷","color":"#D97706"},
        {"name":"Writing",              "emoji":"✍️","color":"#059669"},
        {"name":"Science",              "emoji":"🔬","color":"#0EA5E9"},
        {"name":"Health & Wellness",    "emoji":"💪","color":"#84CC16"},
    ]})

# ═══════════════════════════════════════════════════════════════
if __name__ == "__main__":
    port     = int(os.environ.get("PORT", 5001))
    gem_key  = os.environ.get("GEMINI_API_KEY","")
    groq_key = os.environ.get("GROQ_API_KEY","")
    engine   = os.environ.get("AI_ENGINE","auto")
    print(f"\n  CVhelper.ai v9 — Fully Unique + Full Language Edition   http://localhost:{port}")
    print(f"  Gemini : {'✅ SET' if gem_key  else '❌ not set  ← free key: aistudio.google.com'}")
    print(f"  Groq   : {'✅ SET' if groq_key else '❌ not set  ← free key: console.groq.com'}")
    print(f"  Engine : {engine}")
    print()
    app.run(debug=False, port=port, host="0.0.0.0")
